### PR TITLE
created models

### PR DESCRIPTION
**Pull request by evandev01**
I created all the models, but needs testing. You'll notice I changed the names from plural to singular. With sequelize, when the tables are created, the plurality will automatically be added.

### CODE REVIEW

**Review by bjsmith3185 — APPROVED** [review]

**Comment by evandev01** [comment]
I just pushed #4 a second ago lol. just fyi
*Regards,*

*Evan Bero*
Full-Stack Web Developer
p: 253-533-1753
e: evanbero1980@gmail.com

**Comment by bjsmith3185** [comment]
I just merged 4 as well. I made a fix for the group.js file. It had an extra }    Do a pull before you commit anything else just to absorb that change.

Also.  Do you feel confident about the foreign key changes you made in the Models?  I will not make any changes if you feel this will work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by evandev01** [comment]
Yes, I do. I watched several tutorials before doing that. I can explain
whenever we are able to meet up again.
*Regards,*

*Evan Bero*
Full-Stack Web Developer
p: 253-533-1753
e: evanbero1980@gmail.com

**Comment by bjsmith3185** [comment]
Cool. I was going to look at the videos tonight but I will wait and we can go over what you did. I am going to make some minor changes to the project structure and will let you know when to do a new pull.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by evandev01** [comment]
Sounds good man. ☺
*Regards,*

*Evan Bero*
Full-Stack Web Developer
p: 253-533-1753
e: evanbero1980@gmail.com

**Pull request merged**
